language: python

python:
    - 3.5
    - 3.5-dev
    - 3.6
    - 3.6-dev
 
matrix:
    include:
        - python: 3.7
          dist: xenial
          sudo: true
        - python: 3.7-dev
          dist: xenial
          sudo: true
        - python: 3.8-dev
          dist: xenial
          sudo: true
        - python: nightly
          dist: xenial
          sudo: true

install: pip install .

script: python -m unittest
